<?php

switch ($nivel) {
    case 1:
        $path = '';
        break;
    case 2:
        $path = '../';
        break;
    case 3:
        $path = '../../';
        break;
    default:
        $path = '';
}

define('SESIONES', __DIR__ . '/sesiones.php');
define('FUNCIONES', __DIR__ . '/funciones.php');

define('HEADER', __DIR__ . '/../templates/header.php');
define('BARRA', __DIR__ . '/../templates/barra.php');
define('NAVEGACION', __DIR__ . '/../templates/navegacion.php');
define('FOOTER', __DIR__ . '/../templates/footer.php');

define('PLUGIN', $path . 'plugins/');
define('DIST', $path . 'dist/');
define('MODULOS', $path . 'modulos/');
define('MODELOS', $path . 'modelos/');
define('PRINCIPAL', $path . '');

define('NIVELES', array("1", "2", "3", "4", "5", "6", "7", "8"));

define('GRADOS', [
    1 => array('PRIMERO', 'PRI', 'mat_logros_pri_p', ['U']),
    2 => array('SEGUNDO', 'PRI', 'mat_logros_pri_p', ['U']),
    3 => array('TERCERO', 'PRI', 'mat_logros_pri_p', ['U']),
    4 => array('CUARTO', 'PRI', 'mat_logros_pri_p', ['U']),
    5 => array('QUINTO', 'PRI', 'mat_logros_pri_p', ['U']),
    6 => array('SEXTO', 'SEC', 'mat_logros_sec_p', ['U']),
    7 => array('SÉPTIMO', 'SEC', 'mat_logros_sec_p', ['U']),
    8 => array('OCTAVO', 'SEC', 'mat_logros_sec_p', ['U']),
    9 => array('NOVENO', 'BAC', 'mat_logros_sec_p', ['U']),
    10 => array('DÉCIMO', 'BAC', 'mat_logros_sec_p', ['A', 'B']),
    11 => array('UNDÉCIMO', 'BAC', 'mat_logros_sec_p', ['U']),
    12 => array('PRE JARDÍN', 'TRA', 'mat_logros_tra_p', ['U']),
    13 => array('JARDÍN', 'TRA', 'mat_logros_tra_p', ['U']),
    14 => array('TRANSICIÓN', 'TRA', 'mat_logros_tra_p', ['A', 'B']),
]);

define('GRADOS_COD', [
    "PRIMERO" => 1,
    "SEGUNDO" => 2,
    "TERCERO" => 3,
    "CUARTO" => 4,
    "QUINTO" => 5,
    "SEXTO" => 6,
    "SÉPTIMO" => 7,
    "OCTAVO" => 8,
    "NOVENO" => 9,
    "DÉCIMO" => 10,
    "UNDÉCIMO" => 11,
    "PRE JARDÍN" => 12,
    "JARDÍN" => 13,
    "TRANSICIÓN" => 14,
]);

define('MATERIAS', [
    'SOCIALES' => array('SOC', '#DC3545'),
    'ESPAÑOL' => array('ESP', '#6C757D'),
    'MATEMÁTICAS' => array('MAT', '#17A2B8'),
    'NATURALES' => array('NAT', '#007BFF'),
    'INGLÉS' => array('ING', '#FFC107'),
    'INFORMÁTICA' => array('INF', '#001F3F'),
    'ÉTICA Y RELIGIÓN' => array('EYR', '#6F42C1'),
    'ARTÍSTICA' => array('ART', '#F012BE'),
    'DEPORTE' => array('DEP', '#B8AC17'),
    'MÚSICA' => array('MUS', '#28A745'),
    //'LECTORES' => array('LEC', '#6C757D'),
    'PESP' => array('PES', '#6C757D'),
    'GLOBALIZACIÓN' => array('GLO', '#007BFF'),
    'CORPORAL' => array('COR', '#B8AC17'),
]);

define('SUBDIV', [
    'Inglés' => 'ing',
    'Biología' => 'bio',
    'Química' => 'qui',
    'Física' => 'fis',
    'Castellano' => 'cas',
    'Plan Lector' => 'pla',
    'Aritmética' => 'ari',
    'Geometría' => 'gtr',
    'Estadística' => 'est',
    'Matemáticas' => 'mat',
    'Geografía' => 'geo',
    'Historia' => 'his',
    'Democracia y Paz' => 'dec',
    'Economía Política' => 'eco',
    'Filosofía' => 'fil',
    'Informática' => 'inf',
    'Ética' => 'etc',
    'Religión' => 'reg',
    'Deporte' => 'dep',
    'Música' => 'mus',
    'Arte' => 'art',
    'Globalización' => 'glo',
    'Pesp' => 'pes',
    'Corporal' => 'cor',
]);

define('PERIODOS', [
    1 => 'PRIMERO',
    2 => 'SEGUNDO',
    3 => 'TERCERO',
    4 => 'CUARTO',
    5 => 'QUINTO'
]);

define('RENDIMIENTOS', [
    'TRA' => [
        '0' => array('BAJO', 'danger', 3),
        '0.0' => array('BAJO', 'danger', 3),
        '0.1' => array('BAJO', 'danger', 3),
        '0.2' => array('BAJO', 'danger', 3),
        '0.3' => array('BAJO', 'danger', 3),
        '0.4' => array('BAJO', 'danger', 3),
        '0.5' => array('BAJO', 'danger', 3),
        '0.6' => array('BAJO', 'danger', 3),
        '0.7' => array('BAJO', 'danger', 3),
        '0.8' => array('BAJO', 'danger', 3),
        '0.9' => array('BAJO', 'danger', 3),
        '1.0' => array('BAJO', 'danger', 3),
        '1' => array('BAJO', 'danger', 3),
        '1.1' => array('BAJO', 'danger', 3),
        '1.2' => array('BAJO', 'danger', 3),
        '1.3' => array('BAJO', 'danger', 3),
        '1.4' => array('BAJO', 'danger', 3),
        '1.5' => array('BAJO', 'danger', 3),
        '1.6' => array('BAJO', 'danger', 3),
        '1.7' => array('BAJO', 'danger', 3),
        '1.8' => array('BAJO', 'danger', 3),
        '1.9' => array('BAJO', 'danger', 3),
        '2.0' => array('BAJO', 'danger', 3),
        '2' => array('BAJO', 'danger', 3),
        '2.1' => array('BAJO', 'danger', 3),
        '2.2' => array('BAJO', 'danger', 3),
        '2.3' => array('BAJO', 'danger', 3),
        '2.4' => array('BAJO', 'danger', 3),
        '2.5' => array('BAJO', 'danger', 3),
        '2.6' => array('BAJO', 'danger', 3),
        '2.7' => array('BAJO', 'danger', 3),
        '2.8' => array('BAJO', 'danger', 2),
        '2.9' => array('BAJO', 'danger', 2),
        '3.0' => array('BAJO', 'danger', 1),
        '3' => array('BAJO', 'danger', 1),
        '3.1' => array('BAJO', 'danger', 1),
        '3.2' => array('BÁSICO', 'warning', 3),
        '3.3' => array('BÁSICO', 'warning', 3),
        '3.4' => array('BÁSICO', 'warning', 3),
        '3.5' => array('BÁSICO', 'warning', 2),
        '3.6' => array('BÁSICO', 'warning', 2),
        '3.7' => array('BÁSICO', 'warning', 2),
        '3.8' => array('BÁSICO', 'warning', 1),
        '3.9' => array('BÁSICO', 'warning', 1),
        '4.0' => array('ALTO', 'success', 3),
        '4' => array('ALTO', 'success', 3),
        '4.1' => array('ALTO', 'success', 3),
        '4.2' => array('ALTO', 'success', 3),
        '4.3' => array('ALTO', 'success', 2),
        '4.4' => array('ALTO', 'success', 2),
        '4.5' => array('ALTO', 'success', 1),
        '4.6' => array('SUPERIOR', 'dark', 3),
        '4.7' => array('SUPERIOR', 'dark', 3),
        '4.8' => array('SUPERIOR', 'dark', 2),
        '4.9' => array('SUPERIOR', 'dark', 2),
        '5.0' => array('SUPERIOR', 'dark', 1),
        '5' => array('SUPERIOR', 'dark', 1)
    ],
    'PRI' => [
        '0' => array('BAJO', 'danger', 3),
        '0.0' => array('BAJO', 'danger', 3),
        '0.1' => array('BAJO', 'danger', 3),
        '0.2' => array('BAJO', 'danger', 3),
        '0.3' => array('BAJO', 'danger', 3),
        '0.4' => array('BAJO', 'danger', 3),
        '0.5' => array('BAJO', 'danger', 3),
        '0.6' => array('BAJO', 'danger', 3),
        '0.7' => array('BAJO', 'danger', 3),
        '0.8' => array('BAJO', 'danger', 3),
        '0.9' => array('BAJO', 'danger', 3),
        '1.0' => array('BAJO', 'danger', 3),
        '1' => array('BAJO', 'danger', 3),
        '1.1' => array('BAJO', 'danger', 3),
        '1.2' => array('BAJO', 'danger', 3),
        '1.3' => array('BAJO', 'danger', 3),
        '1.4' => array('BAJO', 'danger', 3),
        '1.5' => array('BAJO', 'danger', 3),
        '1.6' => array('BAJO', 'danger', 3),
        '1.7' => array('BAJO', 'danger', 3),
        '1.8' => array('BAJO', 'danger', 3),
        '1.9' => array('BAJO', 'danger', 3),
        '2.0' => array('BAJO', 'danger', 3),
        '2' => array('BAJO', 'danger', 3),
        '2.1' => array('BAJO', 'danger', 3),
        '2.2' => array('BAJO', 'danger', 3),
        '2.3' => array('BAJO', 'danger', 3),
        '2.4' => array('BAJO', 'danger', 3),
        '2.5' => array('BAJO', 'danger', 3),
        '2.6' => array('BAJO', 'danger', 3),
        '2.7' => array('BAJO', 'danger', 3),
        '2.8' => array('BAJO', 'danger', 2),
        '2.9' => array('BAJO', 'danger', 2),
        '3.0' => array('BAJO', 'danger', 1),
        '3' => array('BAJO', 'danger', 1),
        '3.1' => array('BAJO', 'danger', 1),
        '3.2' => array('BÁSICO', 'warning', 3),
        '3.3' => array('BÁSICO', 'warning', 3),
        '3.4' => array('BÁSICO', 'warning', 3),
        '3.5' => array('BÁSICO', 'warning', 2),
        '3.6' => array('BÁSICO', 'warning', 2),
        '3.7' => array('BÁSICO', 'warning', 2),
        '3.8' => array('BÁSICO', 'warning', 1),
        '3.9' => array('BÁSICO', 'warning', 1),
        '4.0' => array('ALTO', 'success', 3),
        '4' => array('ALTO', 'success', 3),
        '4.1' => array('ALTO', 'success', 3),
        '4.2' => array('ALTO', 'success', 3),
        '4.3' => array('ALTO', 'success', 2),
        '4.4' => array('ALTO', 'success', 2),
        '4.5' => array('ALTO', 'success', 1),
        '4.6' => array('SUPERIOR', 'dark', 3),
        '4.7' => array('SUPERIOR', 'dark', 3),
        '4.8' => array('SUPERIOR', 'dark', 2),
        '4.9' => array('SUPERIOR', 'dark', 2),
        '5.0' => array('SUPERIOR', 'dark', 1),
        '5' => array('SUPERIOR', 'dark', 1)
    ],
    'SEC' => [
        '0' => array('BAJO', 'danger', 3),
        '0.0' => array('BAJO', 'danger', 3),
        '0.1' => array('BAJO', 'danger', 3),
        '0.2' => array('BAJO', 'danger', 3),
        '0.3' => array('BAJO', 'danger', 3),
        '0.4' => array('BAJO', 'danger', 3),
        '0.5' => array('BAJO', 'danger', 3),
        '0.6' => array('BAJO', 'danger', 3),
        '0.7' => array('BAJO', 'danger', 3),
        '0.8' => array('BAJO', 'danger', 3),
        '0.9' => array('BAJO', 'danger', 3),
        '1.0' => array('BAJO', 'danger', 3),
        '1' => array('BAJO', 'danger', 3),
        '1.1' => array('BAJO', 'danger', 3),
        '1.2' => array('BAJO', 'danger', 3),
        '1.3' => array('BAJO', 'danger', 3),
        '1.4' => array('BAJO', 'danger', 3),
        '1.5' => array('BAJO', 'danger', 3),
        '1.6' => array('BAJO', 'danger', 3),
        '1.7' => array('BAJO', 'danger', 3),
        '1.8' => array('BAJO', 'danger', 3),
        '1.9' => array('BAJO', 'danger', 3),
        '2.0' => array('BAJO', 'danger', 3),
        '2' => array('BAJO', 'danger', 3),
        '2.1' => array('BAJO', 'danger', 3),
        '2.2' => array('BAJO', 'danger', 3),
        '2.3' => array('BAJO', 'danger', 3),
        '2.4' => array('BAJO', 'danger', 3),
        '2.5' => array('BAJO', 'danger', 3),
        '2.6' => array('BAJO', 'danger', 3),
        '2.7' => array('BAJO', 'danger', 3),
        '2.8' => array('BAJO', 'danger', 3),
        '2.9' => array('BAJO', 'danger', 2),
        '3.0' => array('BAJO', 'danger', 2),
        '3' => array('BAJO', 'danger', 2),
        '3.1' => array('BAJO', 'danger', 2),
        '3.2' => array('BAJO', 'danger', 1),
        '3.3' => array('BAJO', 'danger', 1),
        '3.4' => array('BÁSICO', 'warning', 3),
        '3.5' => array('BÁSICO', 'warning', 3),
        '3.6' => array('BÁSICO', 'warning', 2),
        '3.7' => array('BÁSICO', 'warning', 2),
        '3.8' => array('BÁSICO', 'warning', 1),
        '3.9' => array('BÁSICO', 'warning', 1),
        '4.0' => array('BÁSICO', 'warning', 1),
        '4' => array('BÁSICO', 'warning', 1),
        '4.1' => array('ALTO', 'success', 3),
        '4.2' => array('ALTO', 'success', 3),
        '4.3' => array('ALTO', 'success', 2),
        '4.4' => array('ALTO', 'success', 2),
        '4.5' => array('ALTO', 'success', 1),
        '4.6' => array('SUPERIOR', 'dark', 3),
        '4.7' => array('SUPERIOR', 'dark', 3),
        '4.8' => array('SUPERIOR', 'dark', 2),
        '4.9' => array('SUPERIOR', 'dark', 2),
        '5.0' => array('SUPERIOR', 'dark', 1),
        '5' => array('SUPERIOR', 'dark', 1)
    ],
    'BAC' => [
        '0' => array('BAJO', 'danger', 3),
        '0.0' => array('BAJO', 'danger', 3),
        '0.1' => array('BAJO', 'danger', 3),
        '0.2' => array('BAJO', 'danger', 3),
        '0.3' => array('BAJO', 'danger', 3),
        '0.4' => array('BAJO', 'danger', 3),
        '0.5' => array('BAJO', 'danger', 3),
        '0.6' => array('BAJO', 'danger', 3),
        '0.7' => array('BAJO', 'danger', 3),
        '0.8' => array('BAJO', 'danger', 3),
        '0.9' => array('BAJO', 'danger', 3),
        '1.0' => array('BAJO', 'danger', 3),
        '1' => array('BAJO', 'danger', 3),
        '1.1' => array('BAJO', 'danger', 3),
        '1.2' => array('BAJO', 'danger', 3),
        '1.3' => array('BAJO', 'danger', 3),
        '1.4' => array('BAJO', 'danger', 3),
        '1.5' => array('BAJO', 'danger', 3),
        '1.6' => array('BAJO', 'danger', 3),
        '1.7' => array('BAJO', 'danger', 3),
        '1.8' => array('BAJO', 'danger', 3),
        '1.9' => array('BAJO', 'danger', 3),
        '2.0' => array('BAJO', 'danger', 3),
        '2' => array('BAJO', 'danger', 3),
        '2.1' => array('BAJO', 'danger', 3),
        '2.2' => array('BAJO', 'danger', 3),
        '2.3' => array('BAJO', 'danger', 3),
        '2.4' => array('BAJO', 'danger', 3),
        '2.5' => array('BAJO', 'danger', 3),
        '2.6' => array('BAJO', 'danger', 3),
        '2.7' => array('BAJO', 'danger', 3),
        '2.8' => array('BAJO', 'danger', 3),
        '2.9' => array('BAJO', 'danger', 3),
        '3.0' => array('BAJO', 'danger', 3),
        '3' => array('BAJO', 'danger', 3),
        '3.1' => array('BAJO', 'danger', 2),
        '3.2' => array('BAJO', 'danger', 2),
        '3.3' => array('BAJO', 'danger', 2),
        '3.4' => array('BAJO', 'danger', 2),
        '3.5' => array('BAJO', 'danger', 1),
        '3.6' => array('BAJO', 'danger', 1),
        '3.7' => array('BAJO', 'danger', 1),
        '3.8' => array('BÁSICO', 'warning', 3),
        '3.9' => array('BÁSICO', 'warning', 2),
        '4.0' => array('BÁSICO', 'warning', 1),
        '4' => array('BÁSICO', 'warning', 1),
        '4.1' => array('ALTO', 'success', 3),
        '4.2' => array('ALTO', 'success', 3),
        '4.3' => array('ALTO', 'success', 2),
        '4.4' => array('ALTO', 'success', 2),
        '4.5' => array('ALTO', 'success', 1),
        '4.6' => array('SUPERIOR', 'dark', 3),
        '4.7' => array('SUPERIOR', 'dark', 3),
        '4.8' => array('SUPERIOR', 'dark', 2),
        '4.9' => array('SUPERIOR', 'dark', 2),
        '5.0' => array('SUPERIOR', 'dark', 1),
        '5' => array('SUPERIOR', 'dark', 1)
    ],
]);

define('NOVEDADES', [
    'TRA' => [
        'BAJO' => '3.1',
        'BÁSICO' => '3.2'
    ],
    'PRI' => [
        'BAJO' => '3.1',
        'BÁSICO' => '3.2'
    ],
    'SEC' => [
        'BAJO' => '3.3',
        'BÁSICO' => '3.4'
    ],
    'BAC' => [
        'BAJO' => '3.7',
        'BÁSICO' => '3.8'
    ],
]);

define('DGRUPOS', [
    'TRANSICIÓN' => array(3.1, 12.8, 4),
    'PRIMERO' => array(3.1, 12.8, 4),
    'SEGUNDO' => array(3.1, 12.8, 4),
    'TERCERO' => array(3.1, 12.8, 4),
    'CUARTO' => array(3.1, 12.8, 4),
    'QUINTO' => array(3.1, 12.8, 4),
    'SEXTO' => array(3.3, 13.6, 4.4),
    'SÉPTIMO' => array(3.3, 13.6, 4.4),
    'OCTAVO' => array(3.3, 13.6, 4.4),
    'NOVENO' => array(3.7, 15.2, 4.4),
    'DÉCIMO' => array(3.7, 15.2, 4.4),
    'UNDÉCIMO' => array(3.7, 15.2, 4.4)
]);